name: Build Release Artifacts
on:
  release:
    types: [published]
jobs:
  build-deb:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '14'
      - uses: DeLaGuardo/setup-clojure@1.0
        with:
          tools-deps: '1.10.1.507'
      - run: clj -T:build ci
      - run: jpackage @jpackage/common @jpackage/linux
      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: lanchinhos-da-maya-0.1.0-SNAPSHOT-1.0_amd64.deb
          asset_name: lanchinhos-da-maya-0.1.0-SNAPSHOT-1.0_amd64.deb
          asset_content_type: application/vnd.debian.binary-package
  build-dmg:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '14'
      - uses: DeLaGuardo/setup-clojure@1.0
        with:
          tools-deps: '1.10.1.507'
      - run: clj -T:build ci
      - run: jpackage @jpackage/common @jpackage/mac
      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: lanchinhos-da-maya-0.1.0-SNAPSHOT-1.0.dmg
          asset_name: lanchinhos-da-maya-0.1.0-SNAPSHOT-1.0.dmg
          asset_content_type: application/x-apple-diskimage
  build-exe:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: DeLaGuardo/setup-clojure@5.0
        with:
          cli: 1.10.1.693
      - run: clojure -T:build ci
        shell: powershell
      - run: jpackage @jpackage/common @jpackage/windows
      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: lanchinhos-da-maya-0.1.0-SNAPSHOT-1.0.exe
          asset_name: lanchinhos-da-maya-0.1.0-SNAPSHOT-1.0.exe
          asset_content_type: application/vnd.microsoft.portable-executable
